name: wordpress_api
description: A WordPress REST API client for dart with support for WooCommerce
  and custom namespaces.
version: 0.3.0
homepage: https://github.com/dhmgroup/dart-wp

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^3.0.10
  html: ^0.14.0+4
  logger: ^0.9.4
  meta: ^1.2.3
